{% set name = "catalystcoop.ferc_xbrl_extractor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/catalystcoop.ferc_xbrl_extractor-{{ version }}.tar.gz
  sha256: a54af162e91775184993a1100c2596baf75bf5b3d3d8ceb145a2272581abda91

build:
  entry_points:
    - xbrl_extract = ferc_xbrl_extractor.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools-scm
    - pip
  run:
    - python >=3.10,<3.12
    - pydantic >=2,<3
    - coloredlogs >=14.0,<15.1
    - arelle-release >=2.3,<2.12
    - frictionless >=4.4,<5
    - sqlalchemy >=1.4,<3
    - pandas >=1.5,<2.1
    - stringcase >=1.2.0,<1.3.dev0
    - lxml >=4.9.1,<5
    - numpy >=1.16,<2

test:
  imports:
    - ferc_xbrl_extractor
  commands:
    - pip check
    - xbrl_extract --help
  requires:
    - pip

about:
  home: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  summary: A tool for extracting data from FERC XBRL regulatory filings into SQLite databases.
  dev_url: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  doc_url: https://catalystcoop-ferc-xbrl-extractor.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zschira
    - zaneselvans
