{% set name = "catalystcoop.ferc_xbrl_extractor" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/catalystcoop.ferc_xbrl_extractor-{{ version }}.tar.gz
  sha256: d8e09e571c3f545b36946551241efa6c484fe6dd45e633a64880994655bb9545

build:
  entry_points:
    - xbrl_extract = ferc_xbrl_extractor.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools-scm
    - pip
  run:
    - python >=3.10,<3.13
    - arelle-release >=2.3,<3
    - coloredlogs >=14.0,<15.1
    - frictionless >=4.4,<5
    - lxml >=4.9.1,<5
    - numpy >=1.16,<2
    - pandas >=1.5,<2.2
    - pydantic >=2,<3
    - sqlalchemy >=1.4,<3
    - stringcase >=1.2,<2

test:
  imports:
    - ferc_xbrl_extractor
  commands:
    - pip check
    - xbrl_extract --help
  requires:
    - pip

about:
  home: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  summary: A tool for extracting data from FERC XBRL regulatory filings into SQLite databases.
  dev_url: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  doc_url: https://catalystcoop-ferc-xbrl-extractor.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zschira
    - zaneselvans
    - jdangerx
