{% set name = "catalystcoop.ferc_xbrl_extractor" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/catalystcoop.ferc_xbrl_extractor-{{ version }}.tar.gz
  sha256: bc42061b5f2fe72a0720ecd1030c5d33a0f3aa2d4ea1b27d31de619d2143642b

build:
  entry_points:
    - xbrl_extract = ferc_xbrl_extractor.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - setuptools-scm
    - pip
  run:
    - python >=3.8,<3.11
    - pydantic >=1.9,<2
    - coloredlogs >=14.0,<15.1
    - arelle-release >=2.2,<2.3
    - frictionless >=4.4,<5
    - sqlalchemy >=1.4,<2
    - pandas >=1.4,<1.6
    - stringcase >=1.2.0,<1.3.dev0

test:
  imports:
    - ferc_xbrl_extractor
  commands:
    - pip check
    - xbrl_extract --help
  requires:
    - pip

about:
  home: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  summary: A tool for extracting data from FERC XBRL Filings into SQLite Databases.
  dev_url: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  doc_url: https://catalystcoop-ferc-xbrl-extractor.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zschira
    - zaneselvans
